import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle, Award, Users } from 'lucide-react';
const About = () => {
    const expertise = [
        'Más de 20 años de experiencia en ventas',
        'Estrategias de captación de clientes',
        'Optimización de procesos de venta',
        'Marketing digital y automatización',
        'Implementación de soluciones de IA',
        'Transformación digital de negocios'
    ];
    return (_jsx("section", { id: "about", className: "section-padding bg-dark-lighter", children: _jsx("div", { className: "max-w-7xl mx-auto container-padding", children: _jsxs("div", { className: "grid md:grid-cols-2 gap-12 items-center", children: [_jsxs("div", { className: "space-y-6", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-white", children: "Transformando Negocios con Experiencia y Tecnolog\u00EDa" }), _jsxs("div", { className: "space-y-4 text-lg text-gray-400", children: [_jsx("p", { children: "Con m\u00E1s de 20 a\u00F1os de experiencia en el mundo de las ventas, he trabajado en m\u00FAltiples sectores, lo que me ha permitido conocer a fondo las din\u00E1micas y desaf\u00EDos de negocios en diversos \u00E1mbitos." }), _jsx("p", { children: "Este recorrido me ha dado una perspectiva clara de lo que necesitan las empresas para crecer y prosperar: captar m\u00E1s clientes, incrementar la facturaci\u00F3n, mejorar la productividad y optimizar la atenci\u00F3n al cliente." }), _jsx("p", { children: "En los \u00FAltimos a\u00F1os, he complementado esta s\u00F3lida base en ventas con una formaci\u00F3n intensiva en marketing digital e inteligencia artificial, convirti\u00E9ndome en un recurso clave para quienes desean escalar sus negocios de manera innovadora y eficiente." })] }), _jsx("div", { className: "space-y-4 mt-6", children: expertise.map((item, index) => (_jsxs("div", { className: "flex items-start space-x-3", children: [_jsx(CheckCircle, { className: "h-6 w-6 text-primary flex-shrink-0 mt-1" }), _jsx("span", { className: "text-gray-300", children: item })] }, index))) })] }), _jsx("div", { className: "space-y-8", children: _jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsxs("div", { className: "relative", children: [_jsx("img", { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=500", alt: "Consultor\u00EDa de negocios", className: "rounded-lg shadow-lg" }), _jsx("div", { className: "absolute -bottom-4 -right-4 bg-primary text-white p-4 rounded-lg shadow-lg", children: _jsx(Award, { className: "h-6 w-6" }) })] }), _jsxs("div", { className: "relative mt-12", children: [_jsx("img", { src: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&q=80&w=500", alt: "Transformaci\u00F3n digital", className: "rounded-lg shadow-lg" }), _jsx("div", { className: "absolute -top-4 -left-4 bg-dark p-4 rounded-lg shadow-lg", children: _jsx(Users, { className: "h-6 w-6 text-primary" }) })] })] }) })] }) }) }));
};
export default About;
